project:
  type: website

site:
  lang: es 
  languages:
    - id: es
      text: Español
      href: ./es/
      main: true   # <-- ¡ESTA ES LA LÍNEA CLAVE!
    - id: en
      text: English
      href: ./en/
      
  title: "fedegiovannetti.github.io"
  navbar:
    left:
      - href: es/index.qmd
        text: Inicio
      - href: es/CV.qmd
        text: CV
      - href: https://substack.com/@fedegiovannetti?
        text: Blog

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    include-after-body: toggle-lang.html

editor: visual

