project:
  type: website
  output-dir: _site

site:
  site-url: https://fedegiovannetti.github.io/
  title: "fedegiovannetti.github.io"
  lang: es
  home: es/index.qmd

  navbar:
    left:
      - href: es/index.qmd
        text: Inicio
      - href: es/CV.qmd
        text: CV
      - href: https://substack.com/@fedegiovannetti?
        text: Blog

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    include-after-body: toggle-lang.html

editor: visual
